import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mentora — 1:1 Online Mentoring from IIT, NIT, IIM & AIIMS Scholars | Personal Tutors for Class 2-10",
  description:
    "Book affordable 1:1 online classes starting at ₹599/month. Verified mentors from IIT, NIT, IIM & AIIMS for Class 2–10 students. Personalized tutoring in Math, Science, English, Coding, Spoken English, Test Prep, Assignment Help, and Project Help. Learn in Hindi, English & regional languages.",
  keywords: [
    "online tutoring",
    "personal mentoring",
    "IIT mentors",
    "NIT tutors",
    "IIM scholars",
    "AIIMS mentors",
    "online classes",
    "1:1 tutoring",
    "personalized learning",
    "Class 2-10 education",
    "math tutor online",
    "science tutor",
    "english tutor",
    "coding classes",
    "spoken english",
    "test preparation",
    "assignment help",
    "project help",
    "homework help",
    "CBSE tutoring",
    "ICSE tutoring",
    "State board tutoring",
    "affordable online classes",
    "best online tutors India",
    "verified mentors",
    "live online classes",
    "home tuition online",
    "private tutor online",
    "online tuition",
    "virtual classroom",
    "e-learning platform",
    "digital education",
    "personal tutor",
    "subject experts",
    "concept clarity",
    "doubt solving",
    "exam preparation",
    "competitive exams",
    "JEE preparation",
    "NEET preparation",
    "board exams",
    "online coaching",
    "personalized attention",
    "individual learning",
    "custom study plans",
    "flexible timing",
    "learn from home",
    "qualified teachers",
    "experienced faculty",
    "interactive sessions",
    "recorded classes",
    "study materials",
    "practice tests",
    "mock tests",
    "performance tracking",
    "progress reports",
    "parent dashboard",
    "safe learning environment",
    "child-friendly",
    "age-appropriate content",
    "skill development",
    "academic excellence",
    "improve grades",
    "boost confidence",
    "concept mastery",
    "problem-solving skills",
    "critical thinking",
    "analytical skills",
    "language learning",
    "communication skills",
    "english speaking",
    "grammar improvement",
    "vocabulary building",
    "reading comprehension",
    "writing skills",
    "mathematics fundamentals",
    "algebra tutoring",
    "geometry tutoring",
    "calculus basics",
    "science concepts",
    "physics tutoring",
    "chemistry tutoring",
    "biology tutoring",
    "computer science",
    "programming basics",
    "web development",
    "app development",
    "STEM education",
    "coding for kids",
    "robotics",
    "artificial intelligence",
    "machine learning basics",
    "data science for beginners",
    "career guidance",
    "study tips",
    "time management",
    "exam strategies",
    "stress management",
    "motivational support",
    "learning disabilities",
    "special education",
    "remedial classes",
    "advanced learning",
    "gifted education",
    "enrichment programs",
    "summer camps",
    "winter programs",
    "holiday classes",
    "weekend batches",
    "evening classes",
    "early morning classes",
    "flexible schedules",
    "one-on-one sessions",
    "group classes",
    "small batch size",
    "personal attention",
    "individual feedback",
    "doubt clearing sessions",
    "revision classes",
    "crash courses",
    "intensive coaching",
    "quick learning",
    "fast track programs",
    "regular curriculum",
    "syllabus completion",
    "exam-oriented teaching",
    "result-oriented approach",
    "success stories",
    "student testimonials",
    "parent reviews",
    "trusted platform",
    "reliable service",
    "quality education",
    "affordable pricing",
    "value for money",
    "budget-friendly",
    "cost-effective",
    "economical tutoring",
    "discount offers",
    "scholarship programs",
    "free demo class",
    "trial session",
    "sample class",
    "experience session",
    "assessment test",
    "placement test",
    "skill assessment",
    "learning gap analysis",
    "personalized recommendations",
    "adaptive learning",
    "AI-powered learning",
    "smart tutoring",
    "intelligent tutoring system",
    "machine learning tutoring",
    "data-driven education",
    "analytics-based learning",
    "performance analytics",
    "learning analytics",
    "educational technology",
    "edtech platform",
    "online education India",
    "digital learning India",
    "e-learning solutions",
    "virtual tutoring",
    "remote learning",
    "distance education",
    "online study",
    "home learning",
    "self-paced learning",
    "guided learning",
    "structured learning",
    "organized study",
    "systematic approach",
    "methodical teaching",
    "step-by-step learning",
    "progressive curriculum",
    "age-appropriate curriculum",
    "grade-wise content",
    "subject-wise tutoring",
    "topic-wise classes",
    "chapter-wise teaching",
    "concept-wise explanation",
    "example-based learning",
    "practical examples",
    "real-world applications",
    "hands-on learning",
    "experiential learning",
    "activity-based learning",
    "game-based learning",
    "interactive learning",
    "engaging content",
    "interesting lessons",
    "fun learning",
    "enjoyable studies",
    "stress-free learning",
    "pressure-free environment",
    "positive reinforcement",
    "encouragement",
    "motivation",
    "confidence building",
    "self-esteem",
    "academic growth",
    "personal development",
    "holistic education",
    "overall development",
    "character building",
    "life skills",
    "soft skills",
    "communication",
    "collaboration",
    "teamwork",
    "leadership",
    "creativity",
    "innovation",
    "problem-solving",
    "critical analysis",
    "decision making",
    "independent thinking",
    "self-directed learning",
    "autonomous learning",
    "self-motivated learning",
    "lifelong learning",
    "continuous learning",
    "growth mindset",
    "learning attitude",
    "positive attitude",
    "academic success",
    "educational excellence",
    "quality teaching",
    "expert guidance",
    "professional tutors",
    "certified teachers",
    "trained educators",
    "skilled mentors",
    "knowledgeable faculty",
    "subject matter experts",
    "domain experts",
    "industry experts",
    "practicing professionals",
    "working professionals",
    "experienced mentors",
    "seasoned teachers",
    "veteran educators",
    "qualified instructors",
    "competent tutors",
    "capable mentors",
    "effective teaching",
    "efficient learning",
    "optimal results",
    "maximum benefit",
    "best outcomes",
    "desired results",
    "target achievement",
    "goal accomplishment",
    "academic goals",
    "learning objectives",
    "educational targets",
    "performance goals",
    "improvement targets",
    "grade improvement",
    "score enhancement",
    "rank improvement",
    "competitive advantage",
    "edge over others",
    "stand out",
    "excel in studies",
    "shine academically",
    "top performer",
    "high achiever",
    "academic star",
    "scholar",
    "merit student",
    "bright student",
    "talented student",
    "gifted child",
    "promising student",
    "future leader",
    "successful career",
    "bright future",
    "career success",
    "professional success",
    "life success",
    "educational success",
    "academic achievements",
    "learning milestones",
    "educational milestones",
    "personal milestones",
    "growth milestones",
    "development milestones",
    "success stories",
    "transformation stories",
    "improvement stories",
    "journey of success",
    "path to excellence",
    "road to success",
    "way to achievement",
    "route to accomplishment",
    "destination of success",
    "goal realization",
    "dream achievement",
    "aspiration fulfillment",
    "ambition realization",
    "vision accomplishment",
    "mission success",
    "purpose achievement",
    "objective fulfillment",
    "target attainment",
    "aim completion",
    "end result",
    "final outcome",
    "ultimate success",
    "complete transformation",
    "total development",
    "overall growth",
    "comprehensive improvement",
    "holistic progress",
    "all-round development",
    "multi-dimensional growth",
    "全方位发展",
    "complete education",
    "full-fledged learning",
    "thorough understanding",
    "deep knowledge",
    "strong foundation",
    "solid base",
    "robust basics",
    "firm grounding",
    "clear concepts",
    "strong fundamentals",
    "deep insight",
    "profound understanding",
    "comprehensive knowledge",
    "extensive learning",
    "broad perspective",
    "wide outlook",
    "global vision",
    "international perspective",
    "worldview",
    "cosmopolitan outlook",
    "modern education",
    "contemporary learning",
    "current curriculum",
    "updated syllabus",
    "latest teaching methods",
    "modern pedagogy",
    "innovative teaching",
    "creative instruction",
    "novel approaches",
    "fresh techniques",
    "new methodologies",
    "advanced strategies",
    "cutting-edge education",
    "state-of-the-art learning",
    "latest technology",
    "modern tools",
    "digital resources",
    "online resources",
    "educational apps",
    "learning software",
    "teaching platforms",
    "virtual classrooms",
    "digital whiteboards",
    "interactive tools",
    "multimedia content",
    "video lessons",
    "audio content",
    "visual aids",
    "graphic organizers",
    "mind maps",
    "concept maps",
    "flowcharts",
    "diagrams",
    "illustrations",
    "animations",
    "simulations",
    "virtual labs",
    "online experiments",
    "digital assessments",
    "online quizzes",
    "virtual tests",
    "digital homework",
    "online assignments",
    "electronic submissions",
    "digital feedback",
    "online reports",
    "virtual progress tracking",
    "digital portfolios",
    "e-records",
    "online certificates",
    "digital badges",
    "virtual achievements",
    "online recognition",
    "digital rewards",
    "gamification",
    "learning games",
    "educational puzzles",
    "interactive quizzes",
    "fun activities",
    "engaging exercises",
    "interesting challenges",
    "motivational tasks",
    "reward-based learning",
    "achievement unlocked",
    "level completion",
    "progress tracking",
    "skill badges",
    "knowledge points",
    "learning streaks",
    "daily challenges",
    "weekly goals",
    "monthly targets",
    "seasonal programs",
    "special courses",
    "thematic classes",
    "topic-specific sessions",
    "subject-focused tutoring",
    "exam-oriented coaching",
    "test-specific preparation",
    "competition training",
    "olympiad preparation",
    "scholarship exam coaching",
    "entrance exam guidance",
    "admission test preparation",
    "placement test coaching",
    "aptitude training",
    "reasoning skills",
    "logical thinking",
    "mental ability",
    "quantitative aptitude",
    "verbal ability",
    "english proficiency",
    "language skills",
    "communication training",
    "personality development",
    "soft skills training",
    "life skills education",
    "career counseling",
    "academic counseling",
    "educational guidance",
    "learning consultation",
    "study advice",
    "exam tips",
    "success strategies",
    "learning techniques",
    "memory techniques",
    "concentration tips",
    "focus improvement",
    "attention building",
    "mindfulness",
    "stress management",
    "anxiety reduction",
    "confidence building",
    "self-improvement",
    "personal growth",
    "skill enhancement",
    "ability development",
    "capacity building",
    "potential unlocking",
    "talent discovery",
    "strength identification",
    "weakness improvement",
    "gap bridging",
    "remedial action",
    "corrective measures",
    "improvement planning",
    "progress monitoring",
    "performance tracking",
    "result analysis",
    "feedback mechanism",
    "continuous improvement",
    "ongoing development",
    "steady progress",
    "consistent growth",
    "regular advancement",
    "continuous learning",
    "never-ending education",
    "lifelong journey",
    "endless possibilities",
    "unlimited potential",
    "boundless opportunities",
    "infinite growth",
    "limitless success",
    "endless achievements",
    "continuous success",
    "perpetual progress",
    "everlasting excellence",
    "timeless quality",
    "ageless wisdom",
    "eternal knowledge",
    "infinite wisdom",
    "boundless knowledge",
    "limitless learning",
    "endless education",
    "unlimited education",
    "infinite opportunities",
    "boundless possibilities",
    "limitless potential",
    "endless potential",
    "continuous potential",
    "perpetual possibilities",
    "everlasting opportunities",
    "timeless opportunities",
    "ageless opportunities",
    "eternal opportunities",
    "infinite opportunities",
    "boundless opportunities",
    "limitless opportunities",
    "endless opportunities"
  ],
  openGraph: {
    title: "Mentora — 1:1 Online Mentoring from IIT, NIT, IIM & AIIMS Scholars",
    description: "Book affordable 1:1 online classes starting at ₹599/month. Verified mentors from IIT, NIT, IIM & AIIMS for Class 2–10 students.",
    url: "https://mentora.in",
    siteName: "Mentora",
    locale: "en_IN",
    type: "website",
    images: [
      {
        url: "https://res.cloudinary.com/dokmhb8tq/image/upload/v1782597564/Modern_Logo_with_Open_Book_and_Digital_Nodes_d07sb6.png",
        width: 1200,
        height: 630,
        alt: "Mentora - 1:1 Online Mentoring",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mentora — 1:1 Online Mentoring from IIT, NIT, IIM & AIIMS Scholars",
    description: "Book affordable 1:1 online classes starting at ₹599/month. Verified mentors from IIT, NIT, IIM & AIIMS for Class 2–10 students.",
    images: ["https://res.cloudinary.com/dokmhb8tq/image/upload/v1782597564/Modern_Logo_with_Open_Book_and_Digital_Nodes_d07sb6.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "your-google-verification-code",
  },
  other: {
    "application/ld+json": JSON.stringify({
      "@context": "https://schema.org",
      "@type": "EducationalOrganization",
      name: "Mentora",
      description: "1:1 online mentoring from IIT, NIT, IIM & AIIMS scholars for Class 2-10 students",
      url: "https://mentora.in",
      logo: "https://res.cloudinary.com/dokmhb8tq/image/upload/v1782597564/Modern_Logo_with_Open_Book_and_Digital_Nodes_d07sb6.png",
      contactPoint: {
        "@type": "ContactPoint",
        telephone: "+91-98765-43210",
        contactType: "customer service",
        email: "Contact.mentoraedu@gmail.com",
        areaServed: "IN",
        availableLanguage: ["Hindi", "English"],
      },
      sameAs: [
        "https://instagram.com/mentoraa.ai",
      ],
      address: {
        "@type": "PostalAddress",
        addressCountry: "IN",
      },
      priceRange: "₹599-₹2999",
      offers: {
        "@type": "Offer",
        price: "599",
        priceCurrency: "INR",
        description: "1-hour online mentoring session",
      },
    }),
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
